// Auto-generated by scripts/generate-env.mjs — do not edit manually.
// Configure values in .env (local) or Vercel Environment Variables (production).

export const environment = {
  production: true,
  apiUrl: 'https://localhost:7229/api',
};
