import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envDir = resolve(root, 'src/environments');

function loadEnvFile() {
  const envPath = resolve(root, '.env');

  if (!existsSync(envPath)) {
    return;
  }

  for (const line of readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const separatorIndex = trimmed.indexOf('=');

    if (separatorIndex === -1) {
      continue;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    const rawValue = trimmed.slice(separatorIndex + 1).trim();
    const value = rawValue.replace(/^(['"])(.*)\1$/, '$2');

    if (!(key in process.env)) {
      process.env[key] = value;
    }
  }
}

function escapeForTsString(value) {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function requireEnv(name) {
  const value = process.env[name]?.trim();

  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }

  return value;
}

function writeEnvironmentFile(fileName, production) {
  const supabaseUrl = escapeForTsString(requireEnv('SUPABASE_URL'));
  const supabaseKey = escapeForTsString(requireEnv('SUPABASE_KEY'));
  const content = `// Auto-generated by scripts/generate-env.mjs — do not edit manually.
// Configure values in .env (local) or Vercel Environment Variables (production).

export const environment = {
  production: ${production},
  supabaseUrl: '${supabaseUrl}',
  supabaseKey: '${supabaseKey}',
};
`;

  writeFileSync(resolve(envDir, fileName), content, 'utf8');
}

loadEnvFile();
writeEnvironmentFile('environment.ts', true);
writeEnvironmentFile('environment.development.ts', false);

console.log('Environment files generated.');
console.log(`  SUPABASE_URL: ${process.env.SUPABASE_URL}`);
